wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.19.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1745984511
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.11.9
      5: 0.19.9
      8:
      - 2
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 2000
lr:
  desc: null
  value: 0.0057626213585251955
weight_decay:
  desc: null
  value: 0.05828739530264579
sheaf_decay:
  desc: null
  value: 0.05828739530264579
early_stopping:
  desc: null
  value: 200
lr_decay_patience:
  desc: null
  value: 20
min_acc:
  desc: null
  value: 0.0
stop_strategy:
  desc: null
  value: loss
d:
  desc: null
  value: 4
layers:
  desc: null
  value: 2
normalised:
  desc: null
  value: true
deg_normalised:
  desc: null
  value: false
linear:
  desc: null
  value: false
hidden_channels:
  desc: null
  value: 64
input_dropout:
  desc: null
  value: 0.2
dropout:
  desc: null
  value: 0.2
left_weights:
  desc: null
  value: true
right_weights:
  desc: null
  value: true
add_lp:
  desc: null
  value: false
add_hp:
  desc: null
  value: false
use_act:
  desc: null
  value: true
second_linear:
  desc: null
  value: false
orth:
  desc: null
  value: householder
sheaf_act:
  desc: null
  value: tanh
edge_weights:
  desc: null
  value: true
sparse_learner:
  desc: null
  value: true
use_bias:
  desc: null
  value: true
dataset:
  desc: null
  value: amazon_ratings
seed:
  desc: null
  value: 43
cuda:
  desc: null
  value: 0
folds:
  desc: null
  value: 10
model:
  desc: null
  value: CoopSheaf
entity:
  desc: null
  value: andrerg00
evectors:
  desc: null
  value: 0
max_t:
  desc: null
  value: 1.0
int_method:
  desc: null
  value: null
step_size:
  desc: null
  value: 1
max_iters:
  desc: null
  value: 100
adjoint_method:
  desc: null
  value: adaptive_heun
adjoint:
  desc: null
  value: false
adjoint_step_size:
  desc: null
  value: 1
tol_scale:
  desc: null
  value: 1.0
tol_scale_adjoint:
  desc: null
  value: 1.0
max_nfe:
  desc: null
  value: 1000
no_early:
  desc: null
  value: false
earlystopxT:
  desc: null
  value: 3
max_test_steps:
  desc: null
  value: 100
num_bundles:
  desc: null
  value: 1
diffusion_time:
  desc: null
  value: 1
gnn_layers:
  desc: null
  value: 1
gnn_hidden:
  desc: null
  value: 32
pe_size:
  desc: null
  value: 0
sha:
  desc: null
  value: 01b2cd20931ca408f529c42bacd7eccaf6ab9af8
graph_size:
  desc: null
  value: 24492
input_dim:
  desc: null
  value: 300
output_dim:
  desc: null
  value: 5
device:
  desc: null
  value: cuda:0
