_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.19.9
            "8":
                - 2
                - 5
            "12": 0.19.9
            "13": linux-x86_64
add_hp:
    value: false
add_lp:
    value: false
adjoint:
    value: false
adjoint_method:
    value: adaptive_heun
adjoint_step_size:
    value: 1
cuda:
    value: 0
d:
    value: 4
dataset:
    value: questions
deg_normalised:
    value: false
device:
    value: cuda:0
diffusion_time:
    value: 1
dropout:
    value: 0.2
early_stopping:
    value: 400
earlystopxT:
    value: 3
edge_weights:
    value: true
entity:
    value: ""
epochs:
    value: 3000
evectors:
    value: 0
folds:
    value: 10
gnn_hidden:
    value: 32
gnn_layers:
    value: 1
graph_size:
    value: 48921
hidden_channels:
    value: 32
input_dim:
    value: 301
input_dropout:
    value: 0.2
int_method:
    value: null
layers:
    value: 4
left_weights:
    value: true
linear:
    value: false
lr:
    value: 0.0002
lr_decay_patience:
    value: 20
max_iters:
    value: 100
max_nfe:
    value: 1000
max_t:
    value: 1
max_test_steps:
    value: 100
min_acc:
    value: 0
model:
    value: CoopSheaf
no_early:
    value: false
normalised:
    value: true
num_bundles:
    value: 1
orth:
    value: householder
output_dim:
    value: 1
pe_size:
    value: 0
right_weights:
    value: false
second_linear:
    value: false
seed:
    value: 43
sha:
    value: 9f35502221d65fc23a8d32265a43cdf7a5251dc7
sheaf_act:
    value: tanh
sheaf_decay:
    value: 1e-07
sparse_learner:
    value: true
step_size:
    value: 1
stop_strategy:
    value: acc
tol_scale:
    value: 1
tol_scale_adjoint:
    value: 1
use_act:
    value: true
use_bias:
    value: true
weight_decay:
    value: 1e-07
