wandb_version: 1

d:
  value: 5
dataset:
  value: roman_empire
dropout:
  value: 0.04692720370907079
early_stopping:
  value: 100
entity:
  value: andrerg00
gnn_hidden:
  value: 24
gnn_layers:
  value: 1
hidden_channels:
  value: 88
input_dropout:
  value: 0.5679983121747125
layers:
  value: 6
left_weights:
  value: true
lr:
  value: 0.02
lr_decay_patience:
  value: 20
model:
  value: CoopSheaf
normalised:
  value: true
orth:
  value: householder
pe_size:
  value: 0
right_weights:
  value: true
seed:
  value: 0
sparse_learner:
  value: true
use_act:
  value: true
weight_decay:
  value: 0.05991646670459412
