wandb_version: 1

d:
  value: 5
dataset:
  value: roman_empire
dropout:
  value: 0.08982996612158989
early_stopping:
  value: 100
entity:
  value: andrerg00
gnn_hidden:
  value: 24
gnn_layers:
  value: 0
hidden_channels:
  value: 248
input_dropout:
  value: 0.2444554194159807
layers:
  value: 5
left_weights:
  value: true
lr:
  value: 0.02
lr_decay_patience:
  value: 20
model:
  value: CoopSheaf
normalised:
  value: true
orth:
  value: householder
pe_size:
  value: 0
right_weights:
  value: true
seed:
  value: 0
sparse_learner:
  value: true
use_act:
  value: true
weight_decay:
  value: 0.02746030760255728
