wandb_version: 1

d:
  value: 5
dataset:
  value: roman_empire
dropout:
  value: 0.10347317272195626
early_stopping:
  value: 100
entity:
  value: andrerg00
gnn_hidden:
  value: 40
gnn_layers:
  value: 6
hidden_channels:
  value: 112
input_dropout:
  value: 0.02384160753694826
layers:
  value: 5
left_weights:
  value: false
lr:
  value: 0.02
lr_decay_patience:
  value: 20
model:
  value: CoopSheaf
normalised:
  value: true
orth:
  value: householder
pe_size:
  value: 0
right_weights:
  value: true
seed:
  value: 0
sparse_learner:
  value: true
use_act:
  value: true
weight_decay:
  value: 0.029670524959099567
