wandb_version: 1

d:
  value: 2
dataset:
  value: roman_empire
dropout:
  value: 0.5812871176961637
early_stopping:
  value: 100
entity:
  value: andrerg00
gnn_hidden:
  value: 136
gnn_layers:
  value: 6
hidden_channels:
  value: 24
input_dropout:
  value: 0.040870707617691904
layers:
  value: 5
left_weights:
  value: false
lr:
  value: 0.02
lr_decay_patience:
  value: 20
model:
  value: CoopSheaf
normalised:
  value: true
orth:
  value: householder
pe_size:
  value: 0
right_weights:
  value: false
seed:
  value: 0
sparse_learner:
  value: true
use_act:
  value: true
weight_decay:
  value: 0.011219264913805694
