wandb_version: 1

d:
  value: 4
dataset:
  value: amazon_ratings
dropout:
  value: 0.2
early_stopping:
  value: 200
entity:
  value: andrerg00
epochs:
  value: 2000
gnn_hidden:
  value: 32
gnn_layers:
  value: 1
hidden_channels:
  value: 64
input_dropout:
  value: 0.2
layers:
  value: 2
left_weights:
  value: true
lr:
  value: 0.0057626213585251955
lr_decay_patience:
  value: 20
model:
  value: CoopSheaf
normalised:
  value: true
orth:
  value: householder
pe_size:
  value: 0
right_weights:
  value: true
sparse_learner:
  value: true
use_act:
  value: true
weight_decay:
  value: 0.05828739530264579
